{"name": "test_database", "status": "broken", "statusDetails": {"message": "AttributeError: __enter__", "trace": "db_connection = <mysql.connector.connection_cext.CMySQLConnection object at 0x106187a60>\n\n    def test_database(db_connection):\n    \n        with db_connection.cursor() as cursor:\n    \n>           with allure.story('Проверка таблицы Manufacturer'):\nE           AttributeError: __enter__\n\ntest_db.py:32: AttributeError"}, "start": 1698418302222, "stop": 1698418302222, "uuid": "84237b7e-618f-4eca-b80c-290d85fa83d7", "historyId": "dfbc62885ac9c62d7046b2cc63445aff", "testCaseId": "dfbc62885ac9c62d7046b2cc63445aff", "fullName": "test_db#test_database", "labels": [{"name": "suite", "value": "test_db"}, {"name": "host", "value": "alexMBP-14.local"}, {"name": "thread", "value": "45644-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_db"}]}