{"name": "test_table_manufacturer", "status": "broken", "statusDetails": {"message": "mysql.connector.errors.ProgrammingError: 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'INTO manufacturer (name_manufacturer, country_id ) VALUES(\"Apple\", 1)' at line 1", "trace": "self = <mysql.connector.connection_cext.CMySQLConnection object at 0x1041e8850>, query = b'UPDATE INTO manufacturer (name_manufacturer, country_id ) VALUES(\"Apple\", 1)', raw = False, buffered = False\nraw_as_string = False\n\n    @with_context_propagation\n    def cmd_query(\n        self,\n        query: StrOrBytes,\n        raw: Optional[bool] = None,\n        buffered: bool = False,\n        raw_as_string: bool = False,\n    ) -> Optional[Union[CextEofPacketType, CextResultType]]:\n        \"\"\"Send a query to the MySQL server\"\"\"\n        self.handle_unread_result()\n        if raw is None:\n            raw = self._raw\n        try:\n            if not isinstance(query, bytes):\n                query = query.encode(\"utf-8\")\n>           self._cmysql.query(\n                query,\n                raw=raw,\n                buffered=buffered,\n                raw_as_string=raw_as_string,\n                query_attrs=self.query_attrs,\n            )\nE           _mysql_connector.MySQLInterfaceError: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'INTO manufacturer (name_manufacturer, country_id ) VALUES(\"Apple\", 1)' at line 1\n\n../../../../Library/Python/3.9/lib/python/site-packages/mysql/connector/connection_cext.py:639: MySQLInterfaceError\n\nThe above exception was the direct cause of the following exception:\n\ndb_connection = <mysql.connector.connection_cext.CMySQLConnection object at 0x1041e8850>\n\n    def test_table_manufacturer(db_connection):\n        with db_connection.cursor() as cursor:\n            with allure.step('INSERT в таблицу Manufacturer'):\n                cursor.execute('INSERT INTO manufacturer (name_manufacturer, country_id ) VALUES(\"Apple\", 1)')\n                db_connection.commit()\n                assert cursor.fetchone() is None\n    \n            with allure.step('Проверка результата INSERT'):\n                cursor.execute('SELECT * from manufacturer where name_manufacturer = %s', ('Apple',))\n                assert cursor.fetchone() is not None\n    \n            with allure.step('UPDATE в таблице Manufacturer'):\n>               cursor.execute('UPDATE INTO manufacturer (name_manufacturer, country_id ) VALUES(\"Apple\", 1)')\n\ntest_db.py:40: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n../../../../Library/Python/3.9/lib/python/site-packages/mysql/connector/cursor_cext.py:330: in execute\n    result = self._cnx.cmd_query(\n../../../../Library/Python/3.9/lib/python/site-packages/mysql/connector/opentelemetry/context_propagation.py:77: in wrapper\n    return method(cnx, *args, **kwargs)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <mysql.connector.connection_cext.CMySQLConnection object at 0x1041e8850>, query = b'UPDATE INTO manufacturer (name_manufacturer, country_id ) VALUES(\"Apple\", 1)', raw = False, buffered = False\nraw_as_string = False\n\n    @with_context_propagation\n    def cmd_query(\n        self,\n        query: StrOrBytes,\n        raw: Optional[bool] = None,\n        buffered: bool = False,\n        raw_as_string: bool = False,\n    ) -> Optional[Union[CextEofPacketType, CextResultType]]:\n        \"\"\"Send a query to the MySQL server\"\"\"\n        self.handle_unread_result()\n        if raw is None:\n            raw = self._raw\n        try:\n            if not isinstance(query, bytes):\n                query = query.encode(\"utf-8\")\n            self._cmysql.query(\n                query,\n                raw=raw,\n                buffered=buffered,\n                raw_as_string=raw_as_string,\n                query_attrs=self.query_attrs,\n            )\n        except MySQLInterfaceError as err:\n>           raise get_mysql_exception(\n                err.errno, msg=err.msg, sqlstate=err.sqlstate\n            ) from err\nE           mysql.connector.errors.ProgrammingError: 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'INTO manufacturer (name_manufacturer, country_id ) VALUES(\"Apple\", 1)' at line 1\n\n../../../../Library/Python/3.9/lib/python/site-packages/mysql/connector/connection_cext.py:647: ProgrammingError"}, "steps": [{"name": "INSERT в таблицу Manufacturer", "status": "passed", "start": 1698416787107, "stop": 1698416787109}, {"name": "Проверка результата INSERT", "status": "passed", "start": 1698416787109, "stop": 1698416787109}, {"name": "UPDATE в таблице Manufacturer", "status": "broken", "statusDetails": {"message": "mysql.connector.errors.ProgrammingError: 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'INTO manufacturer (name_manufacturer, country_id ) VALUES(\"Apple\", 1)' at line 1\n", "trace": "  File \"/Users/akopotov/Documents/College/Testing/checkpoint_6_dB_test/test_db.py\", line 40, in test_table_manufacturer\n    cursor.execute('UPDATE INTO manufacturer (name_manufacturer, country_id ) VALUES(\"Apple\", 1)')\n  File \"/Users/akopotov/Library/Python/3.9/lib/python/site-packages/mysql/connector/cursor_cext.py\", line 330, in execute\n    result = self._cnx.cmd_query(\n  File \"/Users/akopotov/Library/Python/3.9/lib/python/site-packages/mysql/connector/opentelemetry/context_propagation.py\", line 77, in wrapper\n    return method(cnx, *args, **kwargs)\n  File \"/Users/akopotov/Library/Python/3.9/lib/python/site-packages/mysql/connector/connection_cext.py\", line 647, in cmd_query\n    raise get_mysql_exception(\n"}, "start": 1698416787109, "stop": 1698416787109}], "start": 1698416787107, "stop": 1698416787113, "uuid": "699a97e5-d0c5-4359-b7ec-c6b4622e9e3a", "historyId": "7602d2145fb47dfe4ec3e603a1f4ee46", "testCaseId": "7602d2145fb47dfe4ec3e603a1f4ee46", "fullName": "test_db#test_table_manufacturer", "labels": [{"name": "suite", "value": "test_db"}, {"name": "host", "value": "alexMBP-14.local"}, {"name": "thread", "value": "45241-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_db"}]}